routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Http\Controllers\Admin\PostController;

Route::get('/', 'HomeController@index')->name('home');

Route::get('posts', 'PostController@index')->name('posts');
Route::get('/post/{slug}', 'PostController@details')->name('post.details');
Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');
Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::post('favourite/{post}/add', 'FavouritePostController@add')->name('post.favourite');
    Route::post('post/{post}', 'CommentController@store')->name('comment.store');
});

Route::namespace('Admin')->as('admin.')->prefix('admin')->middleware(['auth', 'admin'])->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::patch('profile-update', 'SettingsController@profileupdate')->name('profile.update');
    Route::patch('password-update', 'SettingsController@passwordupdate')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');

    Route::get('/post/pending', 'PostController@pending')->name('post.pending');
    Route::patch('/post/{id}/approve', 'PostController@approval')->name('post.approve');
    Route::get('/post/favourite', 'PostController@favourite')->name('post.favourite');
    Route::resource('post', 'PostController');

    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('/comment', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('/authors', 'AuthorController@index')->name('author.index');
    Route::delete('/authors/{author}', 'AuthorController@destroy')->name('author.destroy');
});

Route::namespace('Author')->as('author.')->prefix('author')->middleware(['auth', 'author'])->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::patch('profile-update', 'SettingsController@profileupdate')->name('profile.update');
    Route::patch('password-update', 'SettingsController@passwordupdate')->name('password.update');

    Route::get('/post/favourite', 'PostController@favourite')->name('post.favourite');
    Route::resource('post', 'PostController');

    Route::get('/comment', 'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

View::composer('layouts.frontend.partials.footer', function ($view) {
    $categories = Category::all();
    $view->With(compact('categories'));
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class AuthorController extends Controller
{
    public function index(User $user)
    {
        $authors = User::authors()
            ->withCount('posts')
            ->withCount('comments')
            ->withCount('favourite_posts')
            ->get();

        return view('admin.authors', compact('authors'));
    }

    public function destroy($author)
    {
        return User::findOrFail($author)->delete();

        toastr()->success('Author Successfully Deleted', 'Deleted');
        return back();
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notifications\AuthorPostApproved;
use App\Notifications\SubscriberPostNotification;
use App\Subscriber;
use App\Tag;
use App\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Post $post)
    {
        $posts = $post->latest()->get();
        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category, Tag $tag)
    {
        $categories = $category->all();
        $tags       = $tag->all();
        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Post $post, Category $category, Tag $tag)
    {
        $this->validate($request, [
            'title'           => 'required',
            'image'           => 'required',
            'categories'      => 'required',
            'tags'            => 'required',
            'body'            => 'required',
        ]);

        $image = $request->file('image');
        $slug  = str_slug($request->title);

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $request->file('image')->getClientOriginalExtension();

            //Check category/banner Directory exists
            if (!Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }

            //Resize Banner image for category
            $postFeaturedImage = Image::make($image)->resize(1920, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save();
            Storage::disk('public')->put('post/' . $imageName, $postFeaturedImage);
        } else {
            $imageName = 'default.png';
        }

        $post           = new Post();
        $post->user_id  = auth()->id();
        $post->title    = $request->title;
        $post->slug     = $slug;
        $post->image    = $imageName;
        $post->body     = $request->body;
        if ($request->has('status')) {
            $post->status = true;
        } else {
            $post->status = false;
        }
        $post->is_approved = true;

        $post->save();

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        //Notification Send to subscriber
        $subscribers = Subscriber::all();
        foreach ($subscribers as $subscriber) {
            Notification::route('mail', $subscriber->email)
            ->notify(new SubscriberPostNotification($post));
        }

        toastr()->success('Post Successfully Added', 'Created');

        return redirect(route('admin.post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post, Tag $tag, Category $category)
    {
        return view('admin.post.show', compact('post', 'tag', 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post, Tag $tag, Category $category)
    {
        $categories = $category::all();
        $tags       = $tag::all();
        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, [
            'title'           => 'required',
            'image'           => 'image',
            'categories'      => 'required',
            'tags'            => 'required',
            'body'            => 'required',
        ]);

        $image = $request->file('image');
        $slug  = str_slug($request->title);

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $request->file('image')->getClientOriginalExtension();

            //Check category/banner Directory exists
            if (!Storage::disk('public')->exists('post')) {
                Storage::disk('public')->makeDirectory('post');
            }
            // Delete Old Thumbnial
            if (Storage::disk('public')->exists('post/' . $post->image)) {
                Storage::disk('public')->delete('post/' . $post->image);
            }

            //Resize Banner image for category
            $postFeaturedImage = Image::make($image)->resize(1920, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save();
            Storage::disk('public')->put('post/' . $imageName, $postFeaturedImage);
        } else {
            $imageName = $post->image;
        }

        $post->user_id  = auth()->id();
        $post->title    = $request->title;
        $post->slug     = $slug;
        $post->image    = $imageName;
        $post->body     = $request->body;
        if ($request->has('status')) {
            $post->status = true;
        } else {
            $post->status = false;
        }
        $post->is_approved = true;

        $post->update();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        toastr()->success('Post Successfully Updated', 'Updated');

        return redirect(route('admin.post.index'));
    }

    public function pending(Post $post)
    {
        $posts = $post::where('is_approved', false)->get();
        return view('admin.post.pending', compact('posts'));
    }

    public function approval($id)
    {
        $post  = Post::find($id);

        if ($post->is_approved == false) {
            $post->is_approved = true;

            if ($post->user->role_id == 2) {
                $post->user->notify(new AuthorPostApproved($post));
            }
        } else {
            $post->is_approved = false;
        }

        $post->update();

        //Notification Send to subscriber
        $subscribers = Subscriber::all();
        foreach ($subscribers as $subscriber) {
            Notification::route('mail', $subscriber->email)
            ->notify(new SubscriberPostNotification($post));
        }

        toastr()->info('Post Approval Status Changed', 'Changed');

        return back();
    }

    public function favourite(Post $post)
    {
        $posts = auth()->user()->favourite_posts;
        return view('admin.post.favourite', compact('posts'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (Storage::disk('public')->exists('post/' . $post->image)) {
            Storage::disk('public')->delete('post/' . $post->image);
        }

        $post->categories()->detach();
        $post->tags()->detach();

        $post->delete();

        toastr()->success('Post Successfully Deleted', 'Deleted');
        return back();
    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    public function index(Comment $comment)
    {
        $posts = auth()->user()->posts;
        return view('author.comment', compact('posts'));
    }

    public function destroy(Comment $comment)
    {
        if ($comment->user == auth()->user()) {
            $comment->delete();
            toastr()->success('Comment Successfully Deleted', 'Deleted');
        } else {
            toastr()->error('You don\'t have permission to delete this comment', 'Permission Denied');
        }

        return back();
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index() 
    {
        return view('author.dashboard');
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('author.settings');
    }

    public function profileupdate(Request $request, User $user)
    {
        $user  = User::findOrFail(auth()->id());

        $this->validate($request, [
            'name'  => 'required',
            'email' => 'required | email',
            'image' => 'image',
        ]);

        $image = $request->file('image');
        $slug  = str_slug($request->name);

        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug . '-' . $currentDate . '-' . uniqid() . '.' . $request->file('image')->getClientOriginalExtension();

            //Check category/banner Directory exists
            if (!Storage::disk('public')->exists('user')) {
                Storage::disk('public')->makeDirectory('user');
            }
            // Delete Old Thumbnial
            if (Storage::disk('public')->exists('user/' . $user->image)) {
                Storage::disk('public')->delete('user/' . $user->image);
            }

            //Resize Banner image for category
            $postFeaturedImage = Image::make($image)->resize(200, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save();
            Storage::disk('public')->put('user/' . $imageName, $postFeaturedImage);
        } else {
            $imageName = $user->image;
        }

        $user->name  = $request->name;
        $user->email = $request->email;
        $user->image = $imageName;
        $user->about = $request->about;
        $user->update();

        toastr()->success('User Successfully Updated', 'Updated');

        return back();
    }

    public function passwordupdate(Request $request)
    {
        $this->validate($request, [
            'old_password' => 'required',
            'password'     => 'required | confirmed',
        ]);

        $oldPassword = auth()->user()->password;
        if (Hash::check($request->old_password, $oldPassword)) {
            if (Hash::check($request->passsword, $oldPassword)) {
                toastr()->error('New Password Can not be same', 'Matched');
                return back();
            } else {
                $user           = User::find(auth()->id());
                $user->password = Hash::make($request->password);
                $user->update();

                toastr()->success('Password Successfully Updated', 'Updated');

                auth()->logout();
                return back();
            }
        } else {
            toastr()->error('Password Did not match', 'Error');
            return back();
        }
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class PostController extends Controller
{
    public function details(Post $post, $slug, Category $category)
    {
        $post = Post::where('slug', $slug)->status()->approved()->first();

        $blogKey = 'blog_' . $post->id;
        if (!Session::has($blogKey)) {
            $post->increment('view_count');
            Session::put($blogKey, 1);
        }

        $randomPosts = $post::status()->approved()->take(3)->inRandomOrder()->get();
        return view('post', compact('post', 'randomPosts'));
    }

    public function index(Post $post)
    {
        $posts = $post->latest()->status()->approved()->paginate(6);
        return view('posts', compact('posts'));
    }

    public function postByCategory(Category $category, $slug)
    {
        $category = Category::where('slug', $slug)->first();
        $posts    = $category->posts()->status()->approved()->paginate(6);
        return view('category', compact('category', 'posts'));
    }

    public function postByTag(Tag $tag, $slug)
    {
        $tag   = Tag::where('slug', $slug)->first();
        $posts = $tag->posts()->status()->approved()->paginate(6);
        return view('tag', compact('tag', 'posts'));
    }
}

resources/views/author/post/index.blade.php
@extends('layouts.backend.layout')

@section('title', 'Posts')

@push('css')
<link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}"
    rel="stylesheet">
@endpush

@section('main-content')
<div class="container-fluid">
    <div class="block-header">
        <a href="{{ route('author.post.create') }}" class="btn btn-primary waves-effect m-b-10 m-t-20">
            <i class="material-icons">add</i>
            <span>Add New Post</span>
        </a>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        ALL POSTS
                        <span class="badge bg-blue">{{ $posts->count() }}</span>
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>Index</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th class="text-right">
                                        <i class="material-icons">visibility</i>
                                    </th>
                                    <th>Status</th>
                                    <th>Is Approved</th>
                                    <th>Thumbnail</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Index</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th class="text-center">
                                        <i class="material-icons">visibility</i>
                                    </th>
                                    <th>Status</th>
                                    <th>Is Approved</th>
                                    <th>Thumbnail</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Actions</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($posts as $key=>$post)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ str_limit($post->title, 15) }}</td>
                                    <td>{{ $post->user->name }}</td>
                                    <td class="text-center">{{ $post->view_count }}</td>
                                    <td>
                                        @if ($post->status == true)
                                        <span class="badge bg-green">Published</span>
                                        @else
                                        <span class="badge bg-blue">Pending</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if ($post->is_approved == true)
                                        <span class="badge bg-green">Approved</span>
                                        @else
                                        <span class="badge bg-blue">Pending</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <img width="60" src="{{ Storage::url('post/'. $post->image ) }}"
                                            alt="{{ $post->name }}" />
                                    </td>
                                    <td>{{ $post->created_at }}</td>
                                    <td>{{ $post->updated_at }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('author.post.show', $post->id) }}"
                                            class="post-edit btn btn-success waves-effect btn-sm" title="Show Post">
                                            <i class="material-icons">visibility</i>
                                        </a>
                                        <a href="{{ route('author.post.edit', $post->id) }}"
                                            class="post-edit btn btn-info waves-effect btn-sm" title="Edit Post">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <button class="btn btn-danger btn-sm waves-effect" type="submit"
                                            title="Delete Post">
                                            <i class="material-icons" onclick="deletePost({{$post->id}})">delete</i>
                                        </button>
                                        <form id="post-delete-form-{{$post->id}}"
                                            action="{{ route('author.post.destroy', $post->id) }}" method="POST"
                                            class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->
@endsection

@push('js')
<!-- Jquery DataTable Plugin Js -->
<script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}">
</script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@8.17.1/dist/sweetalert2.all.min.js"></script>

<!-- Custom Js -->
<script src="{{ asset('assets/backend/js/admin.js') }}"></script>
<script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>

<!-- Demo Js -->
<script src="{{ asset('assets/backend/js/demo.js') }}"></script>

<!-- Delete Post with Notification Js -->
<script type="text/javascript">
    function deletePost(catId) {
        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
        },
        buttonsStyling: true
        })
        swalWithBootstrapButtons.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, delete it!',
        cancelButtonText: 'No, cancel!',
        reverseButtons: true
        }).then((result) => {
        if (result.value) {
            swalWithBootstrapButtons.fire(
            'Deleted!',
            'Post has been deleted :)',
            'success'
            );
            event.preventDefault();
            document.querySelector('#post-delete-form-'+ catId).submit();
        } else if (
            /* Read more about handling dismissals below */
            result.dismiss === Swal.DismissReason.cancel
        ) {
            swalWithBootstrapButtons.fire(
            'Cancelled',
            'Failed to delete Post ):',
            'error'
            )
        }
        })
    }
</script>

@endpush